[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tefi_program = "3bs3SLqeGU4EMz4aXsVzuMFPjs3yxjjyhCEkB26UfRQc"

[programs.devnet]
tefi_program = "3bs3SLqeGU4EMz4aXsVzuMFPjs3yxjjyhCEkB26UfRQc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 15000

[[test.genesis]]
address = "3bs3SLqeGU4EMz4aXsVzuMFPjs3yxjjyhCEkB26UfRQc"
program = "target/deploy/tefi_program.so"

[scripts]
test = "node --loader ts-node/esm ./node_modules/mocha/bin/mocha.js -t 1000000 \"tests/**/*.ts\""
