[package]
name = "tefi_program"
version = "0.1.0"
description = "Tefi - Decentralized trust-based microcredit & risk pool on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tefi_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
